import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'

const inliune = {
  color: 'var(--brand)'
};

const text = {
  color: 'var(--text1)',
  backgroundColor: 'var(--surface1)',
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p style={inliune}>This is brand color</p>
        <p style={text}>This is text 1 and background 1</p>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
