import type { NextPage } from 'next'
import Head from 'next/head'
import NsSpinner from '../components/ui-elements/loading-spinner/Spinner'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NsSpinner sizeInPx={55}></NsSpinner>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
